Finalize project
mapra99/tic-tac-toe-rspec pull request #4
Opened 2019-08-29 21:38 UTC by BenjaminGarza

2019-08-29 22:26 UTC, maelfosso requested changes
Hello,

You really master how to write test. The result is so awesome !!! 

Before moving forward there are some things that should be improved.
- Please it's not `main-spec.rb` but `main_spec.rb`
- Generally, the tests are separated by class. one file for one class
- Your tests should be improved with **negative scenario**
Also, read the comments below.

Kindly make the suggested changes and re-submit a code review request.
Thanks.

2019-08-29 22:26 UTC, maelfosso commented on spec/main-spec.rb
> +    end
About testing `Board` class
- Test the initialize method
- Add negative scenario

2019-08-29 22:26 UTC, maelfosso commented on spec/main-spec.rb
> +    end
What about the **Draw** state ?

2019-08-31 01:05 UTC, Ispirett approved these changes
Great job with changes made and your porject @BenjaminGarza  @mapra99 :1st_place_medal: :100: 
you can merge now!

#### Optional not required
Its good practice to use `let(varible_name) {Border.new } for initiailzations`
Also, this helps make you test output more readable `--format documentation` 
you can add it to your .rspec file

#### Git/Githubflow reminder.

Friendly reminder: You should use Github/Git Flow in this project. However, changing it now would take too much time.
Please make sure you use Github/Git Flow in the next project. You will find instructions in the Patwright lesson description.

2019-09-02 05:43 UTC, merged